[GH] Use release-3.15 branch for testing GH Action Kitchen tests to avoid failures
```
ERROR: Invalid requirement: 'awsbatch-cli/': Expected end or semicolon (after name and no valid version specifier)
    awsbatch-cli/
               ^
Hint: It looks like a path. File 'awsbatch-cli/' does not exist.
```